name: Expo OTA Update

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'

jobs:
  eas-update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: EAS login
        run: npm run eas:login
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: EAS update (production)
        run: npm run eas:update

